name: LaTeX CI

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.tex'

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX source to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: data-structures-algorithms-databases.tex

      - name: Upload compiled PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: data-structures-algorithms-databases.pdf
          path: data-structures-algorithms-databases.pdf
